spring:
  datasource:
    url: jdbc:mysql://localhost:3307/db?useSSL=false
    username: root
    password: root-password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 200