version: "3.9"
networks:
  test-network:
    driver: bridge
services:
  db:
    image: mysql:8.0.25
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./dbdata:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:3306
    networks:
      - test-network

